services:
  app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Ii250405
    ports:
      - "8096:8096"
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: app_izba
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ii250405
      POSTGRES_DB: postgres
      PGDATA: /data/postgres

    ports:
      - "5432:5432"
    restart: always

#  volumes:
#    db: